[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4"
chrono = "0.4.41"
derive_more = "2.0.1"
dotenvy = "0.15.7"
log = "0.4.27"
mysql = "26"
serde = "1.0.219"
sha2 = "0.10.9"
